version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install boto3 pytest
      - echo Validating prompt templates...
      - python scripts/validate_prompts.py
  build:
    commands:
      - echo Testing Bedrock connectivity...
      - python scripts/test_bedrock_models_simple.py
      - echo Configuring Bedrock Guardrails...
      - python scripts/deploy_guardrails_simple.py configs/guardrails.json
      - echo Building Lambda deployment package...
      - zip -r deployment.zip lambda_function.py prompts/ configs/
  post_build:
    commands:
      - echo Deploying to Lambda...
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://deployment.zip
      - echo Integration tests would run here...
      - echo "✅ CI/CD Pipeline completed successfully!"
artifacts:
  files:
    - deployment.zip
    - model_selection_results.json
    - guardrail_deployment_result.json
