version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install boto3 pytest
      - echo Validating prompt templates...
      - python scripts/validate_prompts.py
  build:
    commands:
      - echo Testing prompts against Bedrock models...
      - python scripts/test_bedrock_models.py
      - echo Configuring Bedrock Guardrails...
      - python scripts/deploy_guardrails.py configs/guardrails.json
      - echo Building Lambda deployment package...
      - zip -r deployment.zip lambda_function.py prompts/ configs/
  post_build:
    commands:
      - echo Deploying to staging environment...
      - aws lambda update-function-code --function-name genai-chatbot-staging --zip-file fileb://deployment.zip
      - echo Running integration tests...
      - python scripts/integration_tests.py --environment staging
artifacts:
  files:
    - deployment.zip
    - model_selection_results.json
    - guardrail_deployment_result.json
